spid_cie_oidc/onboarding/urls.py
from django.conf import settings
from django.urls import path

from .views import (
    onboarding_landing,
    onboarding_registration,
    onboarding_entities,
    onboarding_create_jwk,
    onboarding_convert_jwk,
    onboarding_convert_pem,
    onboarding_resolve_statement,
    onboarding_schemas_federation_entity_endpoints,
    onboarding_validating_trustmark,
    onboarding_decode_jwt,
    onboarding_apply_policy,
    onboarding_validate_md,
    onboarding_schemas_authorization,
    onboarding_schemas_introspection,
    onboarding_schemas_metadata,
    onboarding_schemas_revocation,
    onboarding_schemas_token,
    onboarding_schemas_jwt_client_assertion,
    onboarding_validate_authn_request,
    onboarding_validate_ec,
)

_PREF = getattr(settings, "OIDC_PREFIX", "")

urlpatterns = [
    path(
        f"{_PREF}onboarding/landing",
        onboarding_landing,
        name="oidc_onboarding_landing",
    ),
    path(
        f"{_PREF}onboarding/registration",
        onboarding_registration,
        name="oidc_onboarding_registration",
    ),
    path(
        f"{_PREF}onboarding/entities",
        onboarding_entities,
        name="oidc_onboarding_entities",
    ),
    path(
        f"{_PREF}onboarding/tools/create-jwk",
        onboarding_create_jwk,
        name="oidc_onboarding_create_jwk",
    ),
    path(
        f"{_PREF}onboarding/tools/convert-jwk",
        onboarding_convert_jwk,
        name="oidc_onboarding_convert_jwk",
    ),
    path(
        f"{_PREF}onboarding/convert-pem",
        onboarding_convert_pem,
        name="oidc_onboarding_convert_pem",
    ),
    path(
        f"{_PREF}onboarding/tools/resolve-statement",
        onboarding_resolve_statement,
        name="oidc_onboarding_resolve_statement",
    ),
    path(
        f"{_PREF}onboarding/tools/validating-trustmark",
        onboarding_validating_trustmark,
        name="oidc_onboarding_validating_trustmark",
    ),
    path(
        f"{_PREF}onboarding/tools/decode-jwt",
        onboarding_decode_jwt,
        name="oidc_onboarding_tools_decode_jwt",
    ),
    path(
        f"{_PREF}onboarding/tools/apply-policy",
        onboarding_apply_policy,
        name="oidc_onboarding_tools_apply_policy",
    ),
    path(
        f"{_PREF}onboarding/schemas/federation_entity",
        onboarding_schemas_federation_entity_endpoints,
        name="oidc_onboarding_schemas_federation_entity",
    ),
    path(
        f"{_PREF}onboarding/schemas/authorization",
        onboarding_schemas_authorization,
        name="oidc_onboarding_schemas_Authorization",
    ),
    path(
        f"{_PREF}onboarding/schemas/introspection",
        onboarding_schemas_introspection,
        name="oidc_onboarding_schemas_introspection",
    ),
    path(
        f"{_PREF}onboarding/schemas/metadata",
        onboarding_schemas_metadata,
        name="oidc_onboarding_schemas_metadata",
    ),
    path(
        f"{_PREF}onboarding/schemas/revocation",
        onboarding_schemas_revocation,
        name="oidc_onboarding_schemas_revocation",
    ),
    path(
        f"{_PREF}onboarding/schemas/token",
        onboarding_schemas_token,
        name="oidc_onboarding_schemas_token",
    ),
    path(
        f"{_PREF}onboarding/schemas/jwt/client/assertion",
        onboarding_schemas_jwt_client_assertion,
        name="oidc_onboarding_schemas_jwt_client_assertion",
    ),
    path(
        f"{_PREF}onboarding/tools/validate-md",
        onboarding_validate_md,
        name="oidc_onboarding_validate_md",
    ),
    path(
        f"{_PREF}onboarding/tools/validate-authn-request",
        onboarding_validate_authn_request,
        name="oidc_onboarding_validate_authn_request_jwt",
    ),
    path(
        f"{_PREF}onboarding/tools/validate-ec",
        onboarding_validate_ec,
        name="oidc_onboarding_validate_ec",
    ),
]

spid_cie_oidc/onboarding/forms.py
import logging
from django import forms
from django.utils.translation import gettext_lazy as _
from spid_cie_oidc.entity.validators import validate_public_jwks
from spid_cie_oidc.authority.validators import validate_entity_configuration
from .validators import unique_entity_url
from spid_cie_oidc.entity.models import ENTITY_TYPES
from django.conf import settings

logger = logging.getLogger(__name__)

try:
    OIDCFED_TRUST_ANCHORS = getattr(
        settings, "OIDCFED_TRUST_ANCHORS"
    )
except AttributeError: # pragma: no cover
    OIDCFED_TRUST_ANCHORS = []
    logger.warning(
        "OIDCFED_TRUST_ANCHORS not configured in your settings file."
    )


class OnboardingRegistrationForm(forms.Form):

    organization_name = forms.CharField(
        initial="",
        label=_("Organization Name"),
        error_messages={"required": _("Enter your organization name")},
    )

    url_entity = forms.URLField(
        initial="",
        label=_("Entity URL"),
        error_messages={"required": _("Enter the entity unique identifier (HTTP URL)")},
        validators=[validate_entity_configuration, unique_entity_url],
    )

    authn_buttons_page_url = forms.URLField(
        initial="",
        label=_("URL of the login page, if available"),
        error_messages={
            "required": _(
                "Enter the url of the page where the SPID/CIE button is available"
            )
        },
        required=False,
    )

    auth_request_url = forms.CharField(
        initial="",
        label=_("Authentication request URL, if available"),
        required = False
    )

    contact = forms.EmailField(
        initial="",
        label=_("Contact email"),
        error_messages={"required": _("Enter your contact email")},
    )

    type = forms.ChoiceField(
        choices=[(i, i) for i in ENTITY_TYPES],
        label="",
        error_messages={"required": _("Select a entity type")},
    )

    public_jwks = forms.JSONField(
        initial=list,
        label=_("Public Federation JWKs"),
        error_messages={
            "required": _(
                "Enter the public JWKs published in your Entity Configuration, "
                "as double check."
            )
        },
        validators=[validate_public_jwks],
    )


class OnboardingCreateTrustChain(forms.Form):

    sub = forms.URLField(
        initial="",
        label=_("url of subject"),
        error_messages={"required": _("Enter the subject")},
    )

    type = forms.ChoiceField(
        choices=[(i, i) for i in ENTITY_TYPES],
        label="OpenID Connect Federation entity type",
        error_messages={"required": _("Select a entity type")},
    )

    anchor = forms.ChoiceField(
        choices=[(i, i) for i in OIDCFED_TRUST_ANCHORS],
        label=_("url of the trust anchor"),
        error_messages={"required": _("Enter the url of trust anchor")},
    )


class OnboardingValidatingTrustMarkForm(forms.Form):

    sub = forms.URLField(
        initial="",
        label=_("Url of subject"),
        required=False
    )

    id = forms.URLField(
        initial="",
        label=_("Id"),
        required=False
    )

    trust_mark = forms.CharField(
        initial = "",
        label=_("Enter trust mark"),
        required=False
    )


class OnboardingDecodeForm(forms.Form):

    jwt = forms.CharField(
        initial="",
        label=_("jwt"),
        error_messages={"required": _("Enter a jwt")},
    )

    jwk = forms.JSONField(
        initial=dict,
        label=_("jwk"),
        required=False,
    )

spid_cie_oidc/onboarding/templates/base.html
<!-- Extends default Bootstrap Unical Italia template -->
{% extends 'bootstrap-italia-base.html' %}

{% load static %}
{% load i18n %}

{% block extra_head %}
    {{ block.super }}  
{% endblock extra_head %}

{% block page_title %}
{% trans "OIDC Federation onboarding system" %}
{% endblock page_title %}

<!-- URL link top left -->
{% block header_slim_org_url %}
https://www.spid.gov.it/
{% endblock header_slim_org_url %}

<!-- Name top left -->
{% block header_slim_org_name %}
    {% trans "OIDC Federation onboarding system" %}
{% endblock header_slim_org_name %}

<!-- Mobile slim_org_name -->
{% block header_slim_mobile_org_name %}
    {% trans "OIDC Federation onboarding system" %}
{% endblock header_slim_mobile_org_name %}

<!-- Make empty areas -->
{% block header_mobile_arrow %}{% endblock header_mobile_arrow %}
{% block header_mobile_slim_menu %}{% endblock header_mobile_slim_menu %}

<!-- Logo in Header -->
{% block header_center_logo %}
{% endblock header_center_logo %}

<!-- Organization name in Header -->
{% block header_center_org_name %}
    {% trans "OIDC Federation onboarding system" %}
{% endblock header_center_org_name %}

<!-- Organization description in Header -->
{% block header_center_org_subname %}
    {% trans "OIDC Federation onboarding system" %}
{% endblock header_center_org_subname %}


{% block menu_links %}

<li class="nav-item ">
    <a class="nav-link {% if request.resolver_match.view_name == 'oidc_onboarding_landing' %}active{% endif %}" 
    href="{% url 'oidc_onboarding_landing' %}">
        <span>{% trans 'Home' %}</span>
    </a>
</li>
<li class="nav-item">
    <a class="nav-link {% if request.resolver_match.view_name == 'oidc_onboarding_entities' %}active{% endif %}" 
    href="{% url 'oidc_onboarding_entities' %}">
        <span>{% trans 'Entities onboarded' %}</span>
    </a>
</li>
<li class="nav-item">
    <a class="nav-link {% if request.resolver_match.view_name == 'oidc_onboarding_registration' %}active{% endif %}" 
    href="{% url 'oidc_onboarding_registration' %}">
        <span>{% trans 'Register your entity' %}</span>
    </a>
</li>


<li class="nav-item dropdown megamenu">
    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" aria-expanded="true">
        <span>Tools</span>
        <svg class="icon icon-m">
            <use xlink:href="/static/svg/sprite.svg#it-expand"></use>
        </svg>
    </a>
    <div class="dropdown-menu">
        <div class="row">
            <div class="col-12 col-lg-4">
                <div class="link-list-wrapper">
                    <ul class="link-list">
                        <li>
                            <h3 class="no_toc">JWK</h3>
                        </li>  
                        <li><a class="list-item" href="{% url 'oidc_onboarding_create_jwk'%}">
                            <span>{% trans "Create a jwk" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_convert_jwk'%}?type=private">
                            <span>{% trans "Convert a private JWK to PEM" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_convert_jwk'%}?type=public">
                            <span>{% trans "Convert a public JWK to PEM" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_convert_pem'%}?type=private">
                            <span>{% trans "Convert a private PEM to JWK" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_convert_pem'%}?type=public">
                            <span>{% trans "Convert a public PEM to JWK" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_tools_decode_jwt' %}">
                            <span>{% trans "JWT decode and verification" %}</span></a></li>
                        <li>
                            <h3 class="no_toc">Utils</h3>
                        </li>        
                        <li><a class="list-item" href="{% url 'oidc_onboarding_resolve_statement' %}">
                            <span>{% trans "Resolve entity statement" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_tools_apply_policy' %}">
                            <span>{% trans "Apply policy" %}</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-12 col-lg-4">
                <div class="link-list-wrapper">
                    <ul class="link-list">
                        <li>
                            <h3 class="no_toc">VALIDATORS</h3>
                        </li>        
                        <li><a class="list-item" href="{% url 'oidc_onboarding_validate_md' %}?metadata_type=op_metadata&provider_profile=spid">
                            <span>{% trans "Validate OP metadata spid" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_validate_md' %}?metadata_type=op_metadata&provider_profile=cie">
                            <span>{% trans "Validate OP metadata cie" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_validate_md' %}?metadata_type=rp_metadata&provider_profile=spid">
                            <span>{% trans "Validate RP metadata spid" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_validate_md' %}?metadata_type=rp_metadata&provider_profile=cie">
                            <span>{% trans "Validate RP metadata cie" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_validate_authn_request_jwt'%}?provider_profile=spid">
                            <span>{% trans "Validate Authn Request spid" %}</span></a></li> 
                        <li><a class="list-item" href="{% url 'oidc_onboarding_validate_authn_request_jwt'%}?provider_profile=cie">
                            <span>{% trans "Validate Authn Request cie" %}</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_validate_ec' %}">
                            <span>{% trans "Validate Entity Configuration" %}</span></a></li>  
                        <li><a class="list-item" href="{% url 'oidc_onboarding_validating_trustmark' %}">
                            <span>{% trans "Trust mark validation" %}</span></a></li> 
                    </ul>
                </div>
            </div>
            <div class="col-12 col-lg-4">
                <div class="link-list-wrapper">
                    <ul class="link-list">
                        <li>
                            <h3 class="no_toc">{% trans "Schemas" %}</h3>
                        </li>        
                        <li><a class="list-item" href="{% url 'oidc_onboarding_schemas_federation_entity' %}">
                            <span>Federation Entity Endpoint</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_schemas_Authorization' %}">
                            <span>Authorization Endpoint</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_schemas_introspection' %}">
                            <span>Introspection Endpoint</span></a></li> 
                        <li><a class="list-item" href="{% url 'oidc_onboarding_schemas_metadata' %}">
                            <span>Metadata</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_schemas_token' %}">
                            <span>Token Endpoint</span></a></li> 
                        <li><a class="list-item" href="{% url 'oidc_onboarding_schemas_revocation' %}">
                            <span>Revocation Endpoint</span></a></li>
                        <li><a class="list-item" href="{% url 'oidc_onboarding_schemas_jwt_client_assertion' %}">
                            <span>Jwt client Assertion</span></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</li>
{% endblock menu_links %}

{% block container %}
<div>
    <div class="container pt-2 p-3">
       <div class="row d-lg-flex">
            <div class="col-12">
                <div class="card-wrapper card-space">
                    <div class="card card-bg no-after">
                        <div class="card-body pl-lg-0">
                            <div class="row h-100">
                                {% block centered_container %}{% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock container %}

<!-- Logo in Footer -->
{% block footer_logo %}
{% endblock footer_logo %}

<!-- Organization name in Footer -->
{% block footer_org_name %}
    {% trans "OIDC Federation onboarding system" %}
{% endblock footer_org_name %}

<!-- Organization name in Footer -->
{% block footer_org_subname %}
    {% trans "OIDC Federation onboarding system" %}
{% endblock footer_org_subname %}

{% block extra_scripts %}
{% block bootstrap_italia_validation %}

{% endblock bootstrap_italia_validation %}
{% endblock extra_scripts %}

{% block footer_menu_section %}
{% endblock footer_menu_section %}

spid_cie_oidc/onboarding/templates/onboarding_apply_policy.html
<!-- Extends default Bootstrap Unical Italia template -->
{% extends 'base.html' %}
{% load i18n %}

{% block centered_container %}

<div class="col-12 pl-lg-4">

    <h4 class="text-left">
        {% trans "Apply policy" %}
    </h4>

    <p class="card-title">
        {% trans "Adheres a metadata policy to a metadata statement" %}
    </p>
    <form method="get" action="">
        {% csrf_token %}
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-row">
                    <div class="col-12 form-group my-3">
                        <label for="id_md">
                            <span class="form-label-content">
                                metadata statement
                            </span>
                        </label>
                        <textarea id="id_md" rows="9"
                            name="md">{{ md }}</textarea>
                        
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-12 form-group my-3">
                        <label for="id_policy">
                            <span class="form-label-content">
                                metadata policy
                            </span>
                        </label>
                        <textarea id="id_policy" rows="5"
                            name="policy">{{ policy }}</textarea>
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12">
                <div class="form-row">
                    <div class="col-12 form-group my-3">
                        <label for="id_result">
                            <span class="form-label-content">
                                result
                            </span>
                        </label>
                        <textarea id="id_result" rows="16" disabled
                            name="result">{{ result }}</textarea>
                        
                    </div>
                </div>
            </div>
        </div>
        <input type="submit" name="decode" class="btn btn-lg btn-primary btn-block"
                    value="{% trans 'apply' %}" />
    </form>
    
</div>
{% endblock %}

spid_cie_oidc/onboarding/templates/onboarding_convert_jwk.html
<!-- Extends default Bootstrap Unical Italia template -->
{% extends 'base.html' %}
{% load i18n %}

{% block centered_container %}

<div class="col-12 pl-lg-4">

    <h4 class="text-left">
        {% trans "Convert jwk to pem" %}
    </h4>

    <p class="card-title">
        {% trans "Enter a jwk in the field below to encode it in PEM format." %}
    </p>
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-12 form-group my-3">
                <label for="id_jwk">
                    <span class="form-label-content">
                        Jwk
                    </span>
                </label>
                <textarea id="id_jwk" rows="12" name="jwk">{{ jwk }}</textarea>
            </div>
        </div>
        {% if pem %}
        <h4 class="text-left">
            {% if jwk_type == 'private' %}
                {% trans "Private key" %}
            {% else %}
                {% trans "Public key" %}
            {% endif %}
        </h4>
        <div class="form-row">
            <div class="col-12 form-group my-3">
                <textarea id="private_pem" rows="13" name="private_pem">{{ pem }}</textarea>
            </div>
        </div>
        {% endif %}
        <input type="submit" name="confirm" class="btn btn-lg btn-success btn-block"
            value="{% trans 'Convert to pem' %}" />
    </form>

</div>
{% endblock %}

spid_cie_oidc/onboarding/templates/onboarding_convert_pem.html
<!-- Extends default Bootstrap Unical Italia template -->
{% extends 'base.html' %}
{% load i18n %}

{% block centered_container %}

<div class="col-12 pl-lg-4">

    <h4 class="text-left">
        {% if pem_type == 'private' %}
            {% trans "Convert private pem to jwk" %}
        {% else %}
            {% trans "Convert Public pem to jwk" %}
        {% endif %}
    </h4>

    <p class="card-title">
        {% trans "Enter a pem in the field below to decode it in jwk format." %}
    </p>
    <form method="post" action="">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-12 form-group my-3">
                <label for="id_pem">
                    <span class="form-label-content">
                        Pem
                    </span>
                </label>
                <textarea id="id_pem" rows="12" name="pem">{{ pem }}</textarea>
            </div>
        </div>
        {% if jwk %}
            <h4 class="text-left">
                {% if pem_type == 'private' %}
                    {% trans "Private pem" %}
                {% else %}
                    {% trans "Public pem" %}
                {% endif %}
            </h4>
            <div class="form-row">
                <div class="col-12 form-group my-3">
                    <textarea id="jwk" rows="13" name="jwk">{{ jwk }}</textarea>
                </div>
            </div>
        {% endif %}
        <input type="submit" name="confirm" class="btn btn-lg btn-success btn-block"
            value="{% trans 'Convert to jwk' %}" />
    </form>

</div>
{% endblock %}

spid_cie_oidc/onboarding/templates/onboarding_decode_jwt.html
<!-- Extends default Bootstrap Unical Italia template -->
{% extends 'base.html' %}
{% load i18n %}

{% block centered_container %}

<div class="col-12 pl-lg-4">

    <h4 class="text-left">
        {% trans "JWT decode and verification" %}
    </h4>

    <p class="card-title">
        {% trans "Submit a jwt to decode it, if you submit also a jwk you'll decrypt or verify it." %}
    </p>
    <form method="post" action="">
        {% csrf_token %}
        <div class="row">
            <div class="col-12 col-lg-7">
                {% csrf_token %}
                {% for form_field in form %}
                <div class="form-row">
                    {% if form_field.name == 'jwt' %}
                    <div class="col-12 form-group my-3">
                        <label for="id_{{ form_field.html_name }}">
                            <span class="form-label-content">
                            {{ form_field.label }}
                            </span>
                        </label>
                        <textarea id="id_{{ form_field.html_name }}" rows="14" 
                        name="{{ form_field.name }}">{{ form.jwt.value}}</textarea>
                    </div>
                    {% else %}
                    <div class="col-12 form-group my-3">
                        <label for="id_{{ form_field.html_name }}">
                            <span class="form-label-content mt-4">
                            {{ form_field.label }}
                            </span>
                        </label>
                        <textarea id="id_{{ form_field.html_name }}" rows="6" 
                        name="{{ form_field.name }}">{{ form.jwk.value }}</textarea>
                    </div>
                    
                    {% endif %}
                    <span for="id_{{ form_field.html_name }}" class="text-danger">{{ form_field.errors }}</span>
                </div>
                {% endfor %}
            </div>
            <div class="col-12 col-lg-5">
                <div class="form-row">
                    <div class="col-12 form-group my-3">
                        <label for="id_head">
                            <span class="form-label-content">
                                Head
                            </span>
                        </label>
                        <textarea id="id_head" rows="6" name="head">{{ head }}</textarea>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-12 form-group my-2">
                        <label for="id_payload">
                            Payload
                        </label>
                        <textarea id="id_payload" rows="12" name="payload">{{ payload }}</textarea>
                    </div>
                </div>
                <input type="submit" name="decode" class="btn btn-lg btn-success btn-block"
                    value="{% trans 'decode or verify' %}" />
            </div>
        </div>
    </form>

</div>
{% endblock %}

spid_cie_oidc/onboarding/templates/onboarding_entities.html
<!-- Extends default Bootstrap Unical Italia template -->
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block centered_container %}
<div class="col-12 pl-lg-4">
    <h4 class="text-left">
        {% trans "Entities onboarded"%}
    </h4>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">{% trans "organization name" %}</th>
                <th scope="col">{% trans "url entity" %}</th>
                <th scope="col">{% trans "status" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for entity in entities %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ entity.organization_name }}</td>
                <td>{{ entity.url_entity }}</td>
                {% if entity.status == 'processing' %}
                <td class="complementary-2-color-b1">{{ entity.status }}</td>
                {% elif entity.status == 'failed' %}
                <td class="text-danger">{{ entity.status }}</td>
                {% elif entity.status == 'onboarded' %}
                <td class="analogue-2-color-b2">{{ entity.status }}</td>
                {% else %}
                <td class="text-secondary">{{ entity.status }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <nav class="pagination-wrapper justify-content-center">
        <ul class="pagination">
            {% if entities.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{entities.previous_page_number}}" tabindex="-1" aria-hidden="true">
                    <svg class="icon icon-primary">
                        <use href="{% static 'svg/sprite.svg' %}#it-chevron-left"></use>
                    </svg>
                    <span class="sr-only">{% trans "previous page" %}</span>
                </a>
            </li>
            {% endif %}
            {% for i in entities.paginator.page_range%}
            {% if i == entities.number %}
            <li class="page-item active">
                <a class="page-link" href="?page={{ i }}" aria-current="page">
                    <span class="d-inline-block d-sm-none">{% trans "page" %}</span>{{ i }}
                </a>
            </li>
            {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
            {% endfor %}

            {% if entities.has_next%}
            <li class="page-item">
                <a class="page-link" href="?page={{entities.next_page_number}}">
                    <span class="sr-only">{% trans "next page" %}</span>
                    <svg class="icon icon-primary">
                        <use href="{% static 'svg/sprite.svg' %}#it-chevron-right"></use>
                    </svg>
                </a>
            </li>
            {% endif %}

        </ul>
    </nav>


</div>
{% endblock %}

spid_cie_oidc/onboarding/templates/onboarding_jwk.html
<!-- Extends default Bootstrap Unical Italia template -->
{% extends 'base.html' %}
{% load i18n %}

{% block centered_container %}
<div class="col-12 pl-lg-4">
    <h4 class="text-left">
        {% trans "Create a JWK" %}
    </h4>

    <p class="pt-4 mb-0">
        {% trans "In this page you have a brand new JWK. Refresh the page to gent another one." %}
    </p>

    <div class="form-row">
        <div class="col-12 form-group my-3">
            <textarea id="jwk" rows="14" name="jwk">{{ private_jwk }}</textarea>
        </div>
    </div>

    <p class="pt-4 mb-0">
        {% trans "Here the public version of the previous private JWK." %}
    </p>
    <div class="form-row">
        <div class="col-12 form-group my-3">
            <textarea id="jwk" rows="14" name="jwk">{{ public_jwk }}</textarea>
        </div>
    </div>

</div>
{% endblock %}

spid_cie_oidc/onboarding/templates/onboarding_resolve_statement.html
<!-- Extends default Bootstrap Unical Italia template -->
{% extends 'base.html' %}
{% load i18n %}

{% block centered_container %}

<div class="col-12 pl-lg-4">

    <h4 class="text-left">
        {% trans "Resolve Entity Statement" %}
    </h4>

    <p class="card-title">
        {% trans "By inserting the sub of an entity and the trust anchor you can resolve the statement of the entity" %}
    </p>

    <form method="get" action="">
        {% csrf_token %}
        {% for form_field in form %}

        {% if form_field.field.widget.input_type == 'select'%}
        <div class="bootstrap-select-wrapper my-4">
            <select name="{{ form_field.name }}" id="id_{{ form_field.html_name }}">
                {% for value, label in form_field.field.choices %}
                <option value="{{ value }}" {% if form_field.value == value %} selected {% endif %}>
                    {{ label }}
                </option>
                {% endfor %}
            </select>
            <span for="id_{{ form_field.html_name }}" class="text-danger">{{ form_field.errors }}</span>
        </div>

        {% else %}
        <div class="form-row">
            <div class="col-12 form-group my-2">
                <label for="id_{{ form_field.html_name }}">
                    <span class="form-label-content">
                        {{ form_field.label }}
                    </span>
                </label>
                <input type="{{ form_field.field.widget.input_type }}" class="form-control"
                    id="id_{{ form_field.html_name }}" name="{{ form_field.name }}" value="{{form_field.value}}">
            </div>
            <span for="id_{{ form_field.html_name }}" class="text-danger">{{ form_field.errors }}</span>
        </div>

        {% endif %}
        {% endfor %}

        <div class="form-row">
            <div class="col-12 form-group">
                <textarea id="resolved_statement" rows="13" name="resolved_statement"
                    disabled>{{ resolved_statement }}</textarea>
            </div>
        </div>
        <input type="submit" name="confirm" class="btn btn-lg btn-success btn-block" value="{% trans 'resolve' %}" />
    </form>
</div>
{% endblock %}